defaults:
  - medium
  - _self_

task_name: hopper_stand
exp_group: hopper_stand

video_dir: videos/${exp_group}/exp

episode_len: 60

context_changer:
  _target_: context_changers.NullContextChanger
